# Generated by Django 3.0 on 2020-10-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polen',
            name='nivel_alto',
            field=models.FloatField(default=8),
        ),
        migrations.AddField(
            model_name='polen',
            name='nivel_medio',
            field=models.FloatField(default=3),
        ),
        migrations.AlterField(
            model_name='grupopolinico',
            name='nivel_alto',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='grupopolinico',
            name='nivel_medio',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='polen',
            name='nombre_comun',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='polen',
            name='tipo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='ReporteConcentracion',
        ),
    ]
