# Generated by Django 3.0 on 2020-10-13 02:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pollens', '0002_auto_20201013_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelesPolen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.FloatField()),
                ('nivel_calculado', models.FloatField()),
                ('polen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollens.Polen')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteConcentracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tiempo_total', models.IntegerField(default=1440)),
                ('tiempo_extra', models.IntegerField()),
                ('porcentaje_muestreado', models.FloatField(default=0.1)),
                ('tiempo_real', models.FloatField()),
                ('vol_polen', models.FloatField()),
                ('vol_esporas_hongos', models.FloatField()),
                ('niveles_polen', models.ManyToManyField(related_name='reportes', through='pollens.NivelesPolen', to='pollens.Polen')),
            ],
        ),
        migrations.AddField(
            model_name='nivelespolen',
            name='reporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollens.ReporteConcentracion'),
        ),
    ]
