# Generated by Django 3.0 on 2020-10-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollens', '0004_auto_20201013_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupopolinico',
            name='id',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
