# Generated by Django 3.0 on 2020-10-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollens', '0005_auto_20201017_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polen',
            name='alergenicidad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='polen',
            name='familia',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='polen',
            name='picks_presente',
            field=models.BooleanField(blank=True),
        ),
    ]
