# Generated by Django 3.0 on 2020-10-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollens', '0006_auto_20201017_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polen',
            name='nivel_alto',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='polen',
            name='nivel_medio',
            field=models.FloatField(),
        ),
    ]
