# Generated by Django 3.0 on 2020-10-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollens', '0007_auto_20201017_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupopolinico',
            name='nivel_alto_sumatoria',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grupopolinico',
            name='nivel_medio_sumatoria',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
