# Generated by Django 3.0 on 2020-10-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollens', '0008_auto_20201017_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='polen',
            name='nombre_alergia',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
