# Generated by Django 3.0 on 2020-10-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollens', '0009_auto_20201028_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='polen',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
