# Generated by Django 3.0 on 2020-08-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200830_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='needs_onboarding',
            field=models.BooleanField(default=False),
        ),
    ]
