# Generated by Django 3.0 on 2020-08-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_needs_onboarding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='needs_onboarding',
            field=models.BooleanField(default=True),
        ),
    ]
