# Generated by Django 3.0 on 2020-09-06 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200830_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='date_of_birth',
            new_name='fecha_nacimiento',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='needs_onboarding',
            new_name='necesita_onboarding',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='gender',
            new_name='sexo',
        ),
    ]
