# Generated by Django 3.0 on 2020-10-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollens', '0001_initial'),
        ('users', '0007_auto_20200906_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alergias',
            field=models.ManyToManyField(blank=True, to='pollens.Polen'),
        ),
    ]
