# Generated by Django 3.0 on 2020-09-07 00:13

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0002_auto_20200906_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradadiario',
            name='coordenadas',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=None, null=True, srid=4326),
        ),
    ]
