# Generated by Django 3.0 on 2020-09-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0003_auto_20200907_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradadiario',
            name='comentario',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
