# Generated by Django 3.0 on 2020-09-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0004_entradadiario_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='sintomas',
            field=models.ManyToManyField(null=True, to='symptoms.Sintoma'),
        ),
    ]
