# Generated by Django 3.0 on 2020-09-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0005_auto_20200910_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='sintomas',
            field=models.ManyToManyField(blank=True, to='symptoms.Sintoma'),
        ),
    ]
