# Generated by Django 3.0 on 2020-10-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminoscondiciones',
            name='texto',
            field=models.CharField(max_length=10000),
        ),
    ]
